name: Build and Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up SSH key for deployment
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Clone or update repository on the server
        run: |
          TARGET_DIR="/home/ubuntu/AWS_NODE_AGO24_DESAFIO_02_CORINGA-DEPLOY"
          sudo mkdir -p $TARGET_DIR        # Garantir que o diretório exista
          sudo chown -R $USER:$USER $TARGET_DIR  # Garantir que o usuário tenha permissão
          if [ ! -d "$TARGET_DIR" ]; then
            git clone https://github.com/uber-sleep/-AWS_NODE_AGO24_DESAFIO_02_CORINGA-DEPLOY.git $TARGET_DIR
          else
            cd $TARGET_DIR
            git pull origin master
          fi

      - name: Install dependencies
        run: |
          cd $TARGET_DIR
          npm install --legacy-peer-deps

      - name: Build the application
        run: |
          cd $TARGET_DIR
          npm run build

      - name: Deploy the application
        run: |
          cd $TARGET_DIR
          pm2 restart app || pm2 start app

      - name: Clean up SSH key
        run: rm -f private_key.pem
