name: Build and Deploy Application

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - master  # Replace with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run this job on the latest Ubuntu version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up SSH key for deployment
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Reference the private key stored in GitHub Secrets
        run: |
          echo "$PRIVATE_KEY" > private_key.pem  # Write the private key to a file
          chmod 600 private_key.pem  # Set the appropriate permissions for the key file

      - name: Clone or update repository on the server
        run: |
          TARGET_DIR="/home/ubuntu/AWS_NODE_AGO24_DESAFIO_02_CORINGA-DEPLOY"
          
          # Verifica se o diretório existe e, se não, clona o repositório
          if [ ! -d "$TARGET_DIR" ]; then
            echo "Diretório não encontrado. Clonando o repositório..."
            git clone https://github.com/uber-sleep/-AWS_NODE_AGO24_DESAFIO_02_CORINGA-DEPLOY.git $TARGET_DIR
          else
            echo "Diretório já existe. Atualizando o repositório..."
            cd $TARGET_DIR
            git pull origin master
          fi

      - name: Install dependencies
        run: |
          cd $TARGET_DIR
          npm install --legacy-peer-deps

      - name: Build the application
        run: |
          cd $TARGET_DIR
          npm run build

      - name: Deploy the application
        run: |
          cd $TARGET_DIR
          pm2 restart app || pm2 start app

      - name: Clean up SSH key
        run: rm -f private_key.pem  # Remove the private key file after use for security

    permissions:
      contents: read  # Read access to repository contents
      actions: write  # Permission to perform actions like deployments
      id-token: write  # Optional: grant id-token write access if needed
