name: Build and Deploy Application

on:
  push:
    branches:
      - master # ou o nome da sua branch de produção

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Faz o checkout do código da branch atual

      - name: SSH and run commands
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Chave SSH do repositório secreto
        run: |
          echo "$PRIVATE_KEY" > private_key.pem # Escreve a chave privada em um arquivo
          chmod 600 private_key.pem # Dá permissões apropriadas à chave privada

          # Conecta via SSH e executa os comandos no servidor remoto
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@your-server-ip <<EOF
            # Diretório de destino já existe
            TARGET_DIR="/home/ubuntu/AWS_NODE_AGO24_DESAFIO_02_CORINGA-DEPLOY"
            cd $TARGET_DIR

            # Faz o pull do repositório para garantir que está atualizado
            git pull origin master

            # Instala as dependências, caso necessário
            if [ -f "package.json" ]; then
              npm install
            else
              echo "Erro: package.json não encontrado."
              exit 1
            fi

            # Faz o build da aplicação
            npm run build

            # Reinicia o processo ou serviço com PM2 (ou outro sistema de gerenciamento de processos)
            pm2 restart app || pm2 start app.js --name app # Ajuste conforme necessário

          EOF

          rm -f private_key.pem # Remove a chave privada após o uso
